// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachHistoryFile(arg1, arg2) {
  return window['go']['main']['App']['AttachHistoryFile'](arg1, arg2);
}

export function BatchDecodeForTab(arg1, arg2) {
  return window['go']['main']['App']['BatchDecodeForTab'](arg1, arg2);
}

export function CheckDaemonStatus() {
  return window['go']['main']['App']['CheckDaemonStatus']();
}

export function ClearHistory(arg1) {
  return window['go']['main']['App']['ClearHistory'](arg1);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConnectSession(arg1, arg2) {
  return window['go']['main']['App']['ConnectSession'](arg1, arg2);
}

export function CreateExampleFiles(arg1) {
  return window['go']['main']['App']['CreateExampleFiles'](arg1);
}

export function CreateIdleProcess() {
  return window['go']['main']['App']['CreateIdleProcess']();
}

export function DaemonProcessRunning() {
  return window['go']['main']['App']['DaemonProcessRunning']();
}

export function DetachHistoryFile(arg1) {
  return window['go']['main']['App']['DetachHistoryFile'](arg1);
}

export function DisconnectSession(arg1) {
  return window['go']['main']['App']['DisconnectSession'](arg1);
}

export function EncodeTextForSend(arg1, arg2) {
  return window['go']['main']['App']['EncodeTextForSend'](arg1, arg2);
}

export function ForwardConnect(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForwardConnect'](arg1, arg2, arg3);
}

export function ForwardCreate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ForwardCreate'](arg1, arg2, arg3, arg4);
}

export function GetAutoSendStatus(arg1) {
  return window['go']['main']['App']['GetAutoSendStatus'](arg1);
}

export function GetBuiltinIcons() {
  return window['go']['main']['App']['GetBuiltinIcons']();
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetExternalColorTheme(arg1) {
  return window['go']['main']['App']['GetExternalColorTheme'](arg1);
}

export function GetExternalIconTheme(arg1) {
  return window['go']['main']['App']['GetExternalIconTheme'](arg1);
}

export function GetGoroutines() {
  return window['go']['main']['App']['GetGoroutines']();
}

export function GetHistoryStatus() {
  return window['go']['main']['App']['GetHistoryStatus']();
}

export function GetI18n(arg1) {
  return window['go']['main']['App']['GetI18n'](arg1);
}

export function GetPorts() {
  return window['go']['main']['App']['GetPorts']();
}

export function GetSessionHistory(arg1) {
  return window['go']['main']['App']['GetSessionHistory'](arg1);
}

export function GetSessionStats(arg1) {
  return window['go']['main']['App']['GetSessionStats'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetTheme(arg1) {
  return window['go']['main']['App']['GetTheme'](arg1);
}

export function GetThreads() {
  return window['go']['main']['App']['GetThreads']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWatchedSessions() {
  return window['go']['main']['App']['GetWatchedSessions']();
}

export function ListExternalColorThemes() {
  return window['go']['main']['App']['ListExternalColorThemes']();
}

export function ListExternalI18n() {
  return window['go']['main']['App']['ListExternalI18n']();
}

export function ListExternalIconThemes() {
  return window['go']['main']['App']['ListExternalIconThemes']();
}

export function ListHistoryFiles() {
  return window['go']['main']['App']['ListHistoryFiles']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function LoadAppSettings() {
  return window['go']['main']['App']['LoadAppSettings']();
}

export function LoadExternalI18n(arg1) {
  return window['go']['main']['App']['LoadExternalI18n'](arg1);
}

export function MultistrLoad(arg1) {
  return window['go']['main']['App']['MultistrLoad'](arg1);
}

export function MultistrSave(arg1) {
  return window['go']['main']['App']['MultistrSave'](arg1);
}

export function NewHistoryFile(arg1) {
  return window['go']['main']['App']['NewHistoryFile'](arg1);
}

export function OpenDevTools() {
  return window['go']['main']['App']['OpenDevTools']();
}

export function OpenSession(arg1) {
  return window['go']['main']['App']['OpenSession'](arg1);
}

export function ReadMultistrEntries(arg1) {
  return window['go']['main']['App']['ReadMultistrEntries'](arg1);
}

export function RefreshPorts() {
  return window['go']['main']['App']['RefreshPorts']();
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SearchHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchHistory'](arg1, arg2, arg3, arg4);
}

export function SendData(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendData'](arg1, arg2, arg3);
}

export function SendDataShm(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDataShm'](arg1, arg2, arg3);
}

export function SetAutoSendInterval(arg1, arg2) {
  return window['go']['main']['App']['SetAutoSendInterval'](arg1, arg2);
}

export function SetHistoryEnabled(arg1) {
  return window['go']['main']['App']['SetHistoryEnabled'](arg1);
}

export function SetProcessMode(arg1, arg2) {
  return window['go']['main']['App']['SetProcessMode'](arg1, arg2);
}

export function SetTabEncoding(arg1, arg2) {
  return window['go']['main']['App']['SetTabEncoding'](arg1, arg2);
}

export function ShowFolderInExplorer(arg1) {
  return window['go']['main']['App']['ShowFolderInExplorer'](arg1);
}

export function StartAutoSend(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartAutoSend'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartDaemon() {
  return window['go']['main']['App']['StartDaemon']();
}

export function StartQueueSend(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartQueueSend'](arg1, arg2, arg3);
}

export function StartTabDecoder(arg1) {
  return window['go']['main']['App']['StartTabDecoder'](arg1);
}

export function StopAllTabDecoders() {
  return window['go']['main']['App']['StopAllTabDecoders']();
}

export function StopAutoSend(arg1) {
  return window['go']['main']['App']['StopAutoSend'](arg1);
}

export function StopDaemon() {
  return window['go']['main']['App']['StopDaemon']();
}

export function StopTabDecoder(arg1) {
  return window['go']['main']['App']['StopTabDecoder'](arg1);
}

export function SwitchPort(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchPort'](arg1, arg2, arg3);
}

export function TriggerSend(arg1) {
  return window['go']['main']['App']['TriggerSend'](arg1);
}

export function UnwatchSession(arg1) {
  return window['go']['main']['App']['UnwatchSession'](arg1);
}

export function WatchSession(arg1) {
  return window['go']['main']['App']['WatchSession'](arg1);
}

export function WriteMultistrEntries(arg1, arg2) {
  return window['go']['main']['App']['WriteMultistrEntries'](arg1, arg2);
}

export function WriteSendRing(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteSendRing'](arg1, arg2, arg3);
}
