// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AttachHistoryFile(arg1:string,arg2:string):Promise<void>;

export function BatchDecodeForTab(arg1:Array<string>,arg2:string):Promise<Array<any>>;

export function CheckDaemonStatus():Promise<boolean>;

export function ClearHistory(arg1:string):Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function ConnectSession(arg1:string,arg2:main.SerialConfig):Promise<void>;

export function CreateExampleFiles(arg1:string):Promise<Record<string, any>>;

export function CreateIdleProcess():Promise<string>;

export function DaemonProcessRunning():Promise<boolean>;

export function DetachHistoryFile(arg1:string):Promise<void>;

export function DisconnectSession(arg1:string):Promise<void>;

export function EncodeTextForSend(arg1:string,arg2:string):Promise<string>;

export function ForwardConnect(arg1:string,arg2:main.SerialConfig,arg3:main.SerialConfig):Promise<void>;

export function ForwardCreate(arg1:string,arg2:number,arg3:string,arg4:number):Promise<Record<string, any>>;

export function GetAutoSendStatus(arg1:string):Promise<Record<string, any>>;

export function GetBuiltinIcons():Promise<Record<string, string>>;

export function GetClients():Promise<Array<Record<string, any>>>;

export function GetExternalColorTheme(arg1:string):Promise<Record<string, any>>;

export function GetExternalIconTheme(arg1:string):Promise<Record<string, any>>;

export function GetGoroutines():Promise<Record<string, any>>;

export function GetHistoryStatus():Promise<boolean>;

export function GetI18n(arg1:string):Promise<Record<string, string>>;

export function GetPorts():Promise<Array<Record<string, any>>>;

export function GetSessionHistory(arg1:string):Promise<Record<string, any>>;

export function GetSessionStats(arg1:string):Promise<Record<string, any>>;

export function GetSessions():Promise<Array<Record<string, any>>>;

export function GetTheme(arg1:string):Promise<Record<string, any>>;

export function GetThreads():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function GetWatchedSessions():Promise<Array<string>>;

export function ListExternalColorThemes():Promise<Array<config.ExternalThemeInfo>>;

export function ListExternalI18n():Promise<Array<main.ExternalI18nInfo>>;

export function ListExternalIconThemes():Promise<Array<config.ExternalThemeInfo>>;

export function ListHistoryFiles():Promise<Array<Record<string, any>>>;

export function ListThemes():Promise<Array<config.ThemeInfo>>;

export function LoadAppSettings():Promise<main.AppSettings>;

export function LoadExternalI18n(arg1:string):Promise<Record<string, string>>;

export function MultistrLoad(arg1:string):Promise<string>;

export function MultistrSave(arg1:string):Promise<void>;

export function NewHistoryFile(arg1:string):Promise<void>;

export function OpenDevTools():Promise<void>;

export function OpenSession(arg1:main.SerialConfig):Promise<string>;

export function ReadMultistrEntries(arg1:string):Promise<string>;

export function RefreshPorts():Promise<Array<Record<string, any>>>;

export function SaveAppSettings(arg1:main.AppSettings):Promise<void>;

export function SearchHistory(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Record<string, any>>;

export function SendData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendDataShm(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAutoSendInterval(arg1:string,arg2:number):Promise<void>;

export function SetHistoryEnabled(arg1:boolean):Promise<void>;

export function SetProcessMode(arg1:string,arg2:string):Promise<void>;

export function SetTabEncoding(arg1:string,arg2:string):Promise<void>;

export function ShowFolderInExplorer(arg1:string):Promise<Record<string, any>>;

export function StartAutoSend(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<void>;

export function StartDaemon():Promise<void>;

export function StartQueueSend(arg1:string,arg2:boolean,arg3:number):Promise<void>;

export function StartTabDecoder(arg1:string):Promise<void>;

export function StopAllTabDecoders():Promise<void>;

export function StopAutoSend(arg1:string):Promise<void>;

export function StopDaemon():Promise<void>;

export function StopTabDecoder(arg1:string):Promise<void>;

export function SwitchPort(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function TriggerSend(arg1:string):Promise<void>;

export function UnwatchSession(arg1:string):Promise<void>;

export function WatchSession(arg1:string):Promise<void>;

export function WriteMultistrEntries(arg1:string,arg2:string):Promise<void>;

export function WriteSendRing(arg1:string,arg2:string,arg3:string):Promise<void>;
